### ISSUE TITLE
PHP7 incompatibility

### ISSUE THREAD

**Issue by koloszko** [glavweb/GlavwebUploaderBundle#1]
UploaderManager line 302 should be 
$mediaEntities = $entity->{$property['nameGetFunction']}();
to work properly on PHP7

**Comment by nilov** [comment]
Thank you for your answer! I am not test bundle on PHP7. Create pull request, please.

**Comment by nilov** [comment]
Merged in https://github.com/glavweb/GlavwebUploaderBundle/commit/bac722f62b6bfdd537fe7f68243971d2400725dc
